name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Check types
        run: yarn types

      - name: Test
        run: yarn test:ci

      - name: Bench
        run: yarn bench

      - name: Build
        run: yarn build
